### ISSUE TITLE
Neural Compute Stick  can support TF?I want apply  NCS to TF

### ISSUE THREAD

**Issue by mk123qwe** [PINTO0309/MobileNet-SSDLite-RealSense-TF#2]
your title is “ without Neural Compute Stick(NCS)” .Neural Compute Stick  can not support TF?
I am only familiar with TF.I want apply  NCS to TF.could you give me some suggestions？

**Comment by PINTO0309** [comment]
@mk123qwe 
https://ncsforum.movidius.com/discussion/746/is-it-possible-to-use-tensorflow-ssd-mobilenet-on-ncs

As time is wasted if you are using an ARM processor, we encourage you to use "OpenVINO" on x86_64 processor hardware.
Intel does not seem to have a roadmap corresponding to tensorflow.

**Comment by mk123qwe** [comment]
Thank you for your answer.
I find information that NCS support some caffe model.I prefer to gpu if using  x86_64 processor .I pay more attention to ARM with deeplearning.

**Comment by PINTO0309** [comment]
@mk123qwe 
Conversion from tensorflow to caffe is tough because there are a lot of layers unsupported.
I abandoned it already.
If you succeeded, please tell me.
good luck.

**Comment by PINTO0309** [comment]
Since one week passed, I will close "issue" once.
Please open "issue" again if necessary.
