### ISSUE TITLE
Installing librealsense (Step 9) fails on raspbian stretch while make -j1                       

### ISSUE THREAD

**Issue by cheriyck** [PINTO0309/MobileNet-SSDLite-RealSense-TF#3]
**Your device:**
 Raspberry Pi 3 Model B+  

**Your device's CPU architecture:**
The Pi 3 Model B+ has a 1.4GHz 64-bit quad-core Broadcom Arm Cortex A53-architecture processor   
  
**Your OS:**  
Raspbian Stretch OS - Kernel version: 4.14

Your method for Ubuntu works on my laptop everything is successful ( Ubuntu 18.04)
   
**[Required]** Details of the work you did before the problem occurred:  
<br> I did everything up till step 8 on the raspberry pi and step 9 fails
<br>
<br>
**[Required]** Error message:  
`pi@raspberrypi:~/librealsense $ cd build/`
`pi@raspberrypi:~/librealsense/build $ make -j1`
`[ 58%] Built target tm`
`[ 58%] Built target realsense-file`
`[ 58%] Built target realsense2`
`[ 58%] Linking CXX executable rs-software-device`
`/usr/bin/ld: /usr/local/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'`
`//usr/lib/arm-linux-gnueabihf/libX11.so.6: error adding symbols: DSO missing from command line`
`collect2: error: ld returned 1 exit status`
`examples/software-device/CMakeFiles/rs-software-device.dir/build.make:98: recipe for target examples/software-device/rs-software-device' failed`
`make[2]: *** [examples/software-device/rs-software-device] Error 1`
`CMakeFiles/Makefile2:282: recipe for target 'examples/software-device/CMakeFiles/rs-software-device.dir/all' failed`
`make[1]: *** [examples/software-device/CMakeFiles/rs-software-device.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`
`pi@raspberrypi:~/librealsense/build $  `

**Overview of problems and questions:**  
I followed everything up to step 8 but I can't seem to move past step 9 (installing the SDK). I tried different solutions but I can't seem to get it going. It keeps saying 
`//usr/lib/arm-linux-gnueabihf/libX11.so.6: error adding symbols: DSO missing from command line
`

On my laptop that runs ubuntu I am able to run the object detection script but not on the raspbian stretch.

Is there a work around to this?

Any help is appreciated

**Comment by cheriyck** [comment]
![image](https://user-images.githubusercontent.com/22759712/55024070-7d93a580-4fd4-11e9-8e68-0ae1d673d3de.png)

**Comment by PINTO0309** [comment]
**https://stackoverflow.com/questions/28531014/glew-and-glfw-compile-error-undefined-reference-to-symbol-xconvertselection**
