### ISSUE TITLE
Adding Coral, using RPi 4, and getting X,Y in addition to D

### ISSUE THREAD

**Issue by GOBish** [PINTO0309/MobileNet-SSDLite-RealSense-TF#4]
Hello,
Thank you so much for all your work on this, I am working on a similar project and you have helped me out.
Some questions, maybe you can comment:
1. Have you used the google coral USB accelerator yet? Could you see adding it to this tensor flow project?
2. Have you used the Raspberry Pi 4 with this yet?
3. In addition to getting the depth, d, to the identified object, have you worked out getting the X and Y coordinates as well? Any advice for this?

Thank you!

**Comment by PINTO0309** [comment]
i>1. Have you used the google coral USB accelerator yet? Could you see adding it to this tensor flow project?

No. The purpose of this repository was to verify how much performance can be achieved with Pi3 without using external devices.

>2. Have you used the Raspberry Pi 4 with this yet?

Depending on the priority of the other projects I work on, I can try it if I have time. I am now devoted to verifying Tensorflow Select (Flex delegate). It takes time to start verification with Pi4.

>3. In addition to getting the depth, d, to the identified object, have you worked out getting the X and Y coordinates as well? Any advice for this?

Yes. Just calculate the center point according to the object detection result. `X1 + ((X2 - X1 ) / 2, Y1 + (Y2 - Y1)) / 2` Please note that this is not a standard RealSense feature. Perhaps your intentions are as follows: Simultaneous acquisition of depth and coordinates of a specific point. If so, the RealSense return depth 2D array corresponds to the XY coordinates of the image and can be easily obtained.
