### ISSUE TITLE
Obtain distance from detected object

### ISSUE THREAD

**Issue by gohsnn** [PINTO0309/MobileNet-SSDLite-RealSense-TF#5]
Hello, 

Thank you for your work on this project! I am doing something similar by making use of the D435i and Tensorflow on a Jetson Xavier NX (Ubuntu 18.04) to run object detection inference. 

Would like to get your advice on how to obtain the distance from the object to the camera (as seen in your inference) without making use of OpenGL? 

Thanks in advance!

**Comment by PINTO0309** [comment]
Just superimpose the D435 depth figures on the following implementation.
**https://github.com/PINTO0309/PINTO_model_zoo/blob/master/06_mobilenetv2-ssdlite/02_voc/mobilenetv2ssdlite_usbcam_sync.py**
