### ISSUE TITLE
KeyError: frequency when running code

### ISSUE THREAD

**Issue by garceling** [PINTO0309/MobileNet-SSDLite-RealSense-TF#6]
**[Required]** RaspberryPi3, LaptopPC, or other device name):  RaspberryPi4
  
**[Required]** Your device's CPU architecture (armv7l, x86_64, or other architecture name):  armv7l

**[Required]** Your OS (Raspbian, Ubuntu1604, or other os name):  raspbian buster
  
**[Required]** Details of the work you did before the problem occurred:  I followed the tutorial from github
<br>
<br>
<br>
**[Required]** Error message:  However, I keep on getting this error when I try to run the program:
File "/home/pi/.local/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 866, in HasField
    field = hassable_fields[field_name]
KeyError: 'frequency'

<br>
<br>
<br>
**[Required]** Overview of problems and questions:  During the handling of the above error, another errors occurred. I searched online, and I cannot find the solution. The tensorflow version I am using is 1.14.0. Thank you and any help is appreciated. 
<br>
<br>
<br>

**Comment by PINTO0309** [comment]
As the error message indicates, it is a problem with the protocol buffer.

**Comment by garceling** [comment]
sorry what does this mean, and how can i fix it

**Comment by PINTO0309** [comment]
I haven't tested it in any environment other than the one described in the README, so I think the problem is specific to your environment. The only thing you can try is to match the version of the tool you are installing.
